name: adatyper
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.2
  - python=3.9.5
  - readline=8.1
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.13.0
    - altair==4.1.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - asgiref==3.3.4
    - astroid==2.5.6
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - bottleneck==1.2.1
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - clang==5.0
    - click==8.0.1
    - cycler==0.10.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - deprecated==1.2.12
    - entrypoints==0.3
    - fairseq==0.10.0
    - fasttext==0.9.2
    - filelock==3.4.0
    - flask==2.0.1
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.4.0
    - gdown==4.2.0
    - gensim==3.8.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - grpcio==1.39.0
    - h11==0.12.0
    - h5py==3.1.0
    - htmlmin==0.1.12
    - huggingface-hub==0.1.2
    - idna==2.10
    - imagehash==4.2.1
    - importlib-metadata==4.8.1
    - iniconfig==1.1.1
    - ipykernel==5.5.5
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isort==5.8.0
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonpatch==1.32
    - jsonpointer==2.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mccabe==0.6.1
    - missingno==0.5.0
    - mistune==0.8.4
    - msgpack==1.0.3
    - multimethod==1.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.6.2
    - nltk==3.6.2
    - notebook==6.4.0
    - numpy==1.21.2
    - oauthlib==3.1.1
    - openreview-py==1.0.22
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - phik==0.12.0
    - pickle5==0.0.11
    - pickleshare==0.7.5
    - pillow==8.3.1
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - py==1.10.0
    - py4j==0.10.9
    - pyarrow==4.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pycparser==2.20
    - pycryptodome==3.10.1
    - pydantic==1.8.2
    - pygments==2.9.0
    - pylatexenc==2.10
    - pylint==2.8.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytest==6.2.4
    - python-dateutil==2.8.1
    - python-dotenv==0.18.0
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - redis==4.0.2
    - regex==2021.8.28
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.46
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.2
    - send2trash==1.5.0
    - setuptools==49.6.0
    - six==1.15.0
    - sklearn==0.0
    - smart-open==5.2.1
    - starlette==0.14.2
    - tangled-up-in-unicode==0.1.0
    - termcolor==1.1.0
    - terminado==0.10.0
    - testpath==0.5.0
    - threadpoolctl==2.1.0
    - tld==0.10
    - tokenizers==0.10.3
    - toml==0.10.2
    - toolz==0.11.1
    - torch==1.10.0
    - torch-scatter==1.3.2
    - tornado==6.1
    - tqdm==4.61.2
    - traitlets==5.0.5
    - transformers==4.12.5
    - typing-extensions==3.7.4.3
    - tzlocal==3.0
    - ujson==4.3.0
    - urllib3==1.26.6
    - uvicorn==0.14.0
    - visions==0.7.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.5.0
    - git+https://github.com/huggingface/transformers.git@372a5c1ceec49b52c503707e9657bfaae7c236a0#egg=pytorch_pretrained_bert
